# Generated by Django 3.2.25 on 2024-03-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionsApp', '0002_auto_20240318_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='OwnerId',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Type',
            new_name='type',
        ),
    ]
