# Generated by Django 3.2.25 on 2024-03-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionType',
            new_name='Type',
        ),
    ]
