# Generated by Django 3.2.25 on 2024-04-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionsApp', '0001_squashed_0004_transaction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='ownerId',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tags',
            new_name='user_tags',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='TransactionsApp.category'),
        ),
    ]
