# Generated by Django 3.2.25 on 2024-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionsApp', '0005_alter_transaction_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
    ]
